* sjs

  This is a C library implementing a static jet scheme (SJS) for
  solving the eikonal equation in 2D on a regular grid. Ideally, other
  SJSs will be added as they're developed to reuse some of the
  functionality common to them.

  The library comes with a Python interface written using pybind11 and
  which is a straightforward mapping of the "object-oriented" C
  interface to an object-oriented Python library. All of the "classes"
  in the C library are exposed to make things transparent and simple.

** Compilation

   To compile, just run:
#+BEGIN_SRC sh
$ python setup.py install
#+END_SRC
   This will install a Python module named ~sjs~ which contains
   everything in a flat namespace.

** Tests

   To run the included unit tests, first install the module as
   described above, and then run:
#+BEGIN_SRC sh
$ python -m unittest
#+END_SRC
   This will in turn run the
   tests contained in each of the ~test_*.py~ files.

   Since the Python interface exposes exactly the same interface as
   the C library, we opt to just implement the tests using Python's
   unit testing facilities for simplicity and flexibility. These tests
   do double duty and make sure that the Python bindings are
   implemented correctly, and also that the library's implementation
   itself is correct.

** Tagged versions

   Some important versions are tagged (you can find these under the
   "branches" menu if you're browsing this repository using
   GitHub). Currently, there are the following branches:

   | Tag    | Description                                    |
   |--------+------------------------------------------------|
   | v0.1.1 | First version with ~eik~ working for s \neq 1. |
   | v0.1.0 | First version with ~eik~ working for s \equiv 1. |
